// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/mic_ffi.h`.
///
class MicFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MicFfiBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MicFfiBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>>(
        'sum',
      );
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  int init_mic() {
    return _init_mic();
  }

  late final _init_micPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>(
    'init_mic',
  );
  late final _init_mic = _init_micPtr.asFunction<int Function()>();

  double get_amplitude() {
    return _get_amplitude();
  }

  late final _get_amplitudePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('get_amplitude');
  late final _get_amplitude = _get_amplitudePtr.asFunction<double Function()>();

  void stop_mic() {
    return _stop_mic();
  }

  late final _stop_micPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'stop_mic',
  );
  late final _stop_mic = _stop_micPtr.asFunction<void Function()>();
}
